import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cybercore Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-gray-900 text-purple-100`}
      >
        <header className="border-b border-purple-500/30 bg-gray-900/80 backdrop-blur-sm sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-16">
              <div className="flex items-center">
                <Link
                  href="/"
                  className="text-xl font-semibold text-purple-300 hover:text-purple-100 transition-colors"
                >
                  <span className="font-mono">CYBER</span>LOGO
                </Link>
              </div>
              <nav className="flex space-x-8">
                <Link
                  href="/"
                  className="text-sm text-purple-300 hover:text-purple-100 transition-colors"
                >
                  MAINFRAME
                </Link>
                <Link
                  href="/about"
                  className="text-sm text-purple-300 hover:text-purple-100 transition-colors"
                >
                  NEURAL_NET
                </Link>
                <Link
                  href="/contact"
                  className="text-sm text-purple-300 hover:text-purple-100 transition-colors"
                >
                  UPLINK
                </Link>
              </nav>
            </div>
          </div>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="border-t border-purple-500/30 bg-gray-900">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div>
                <h3 className="text-sm font-semibold mb-4 text-purple-300">
                  SYSTEM_INFO
                </h3>
                <p className="text-sm text-purple-200/70">
                  Next-gen digital solutions for the cybernetic age.
                </p>
              </div>
              <div>
                <h3 className="text-sm font-semibold mb-4 text-purple-300">
                  PROTOCOLS
                </h3>
                <ul className="space-y-2">
                  <li>
                    <Link
                      href="/terms"
                      className="text-sm text-purple-200/70 hover:text-purple-100 transition-colors"
                    >
                      SECURITY_TERMS
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/privacy"
                      className="text-sm text-purple-200/70 hover:text-purple-100 transition-colors"
                    >
                      DATA_SHIELD
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="text-sm font-semibold mb-4 text-purple-300">
                  DATALINK
                </h3>
                <p className="text-sm text-purple-200/70">
                  nexus@cybercore.net
                  <br />
                  GRID: 0xF3A2-B901
                </p>
              </div>
            </div>
            <div className="mt-8 pt-8 border-t border-purple-500/30 text-center text-sm text-purple-200/70">
              © {new Date().getFullYear()} Your Company. All rights reserved.
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
